apiVersion: apps/v1
kind: Deployment
metadata:
  name: refty-bayut-district-property-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: refty-bayut-district-property-sync
  template:
    metadata:
      labels:
        app: refty-bayut-district-property-sync
    spec:
      containers:
      - command:
        - node
        - dist/bayutDistrictSyncManager.js
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: postgres-secret
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: postgres-secret
        - name: POSTGRES_HOST
          value: postgres
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_PORT
          value: '5432'
        image: ghcr.io/refty-yapi/refty-node/refty-node:05-06-test123
        name: refty-bayut-district-property-sync
        volumeMounts:
        - mountPath: /app/config
          name: refty-node-config
      imagePullSecrets:
      - name: regcred
      nodeSelector:
        purpose: parsers
      serviceAccountName: refty-dev-new
      tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: parsers
      volumes:
      - configMap:
          name: refty-node-config
        name: refty-node-config
